[[languages.cpp.environments]]
CXX = "g++"
CXXFLAGS = [
    "-std=gnu++23",
    "-O2",
    "-D_FORTIFY_SOURCE=2",
    "-fdiagnostics-color=always",
    "-fno-sanitize-recover",
    "-fsanitize=undefined,address",
    "-Wall",
    "-Wextra",
    "-Wshadow",
    "-Wformat=2",
    "-Wfloat-equal",
    "-Wconversion",
    "-Wlogical-op",
    "-Wshift-overflow=2",
    "-Wduplicated-cond",
    "-Wcast-qual",
    "-Wcast-align=strict"
]
